version: '3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    networks:
     - dvs
    volumes:
     - ${LOCAL_VPN_CONFIG_PATH}:/etc/openvpn
    restart: always
