version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    networks:
      - dvs
    volumes:
      - ${DVS_LOCAL_VPN_CONFIG_PATH}:/etc/openvpn
    restart: always

  samba:
    container_name: samba
    build: .
    volumes:
      - ${DVS_LOCAL_SHARE_PATH}:/samba
    networks:
      dvs:
          ipv4_address: 172.28.28.28
    restart: "always"

networks:
  dvs:
      ipam:
          driver: default
          config:
              - subnet: 172.28.28.0/24